name: NODE CI
on: [push]
jobs:
  test-build:
    name: Test & build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 15
      - run: yarn
      # Build modules
      - run: yarn build
      # Build sonar reports
      - run: yarn test-coverage
      - name: Create file ${{ inputs.tag }}
        run: |
          ls
          echo "sonar.branch.name=master" >> sonar-project.properties
          echo "sonar.organization=cabunga-github" >> sonar-project.properties
          echo "sonar.projectKey=cabunga-github_node" >> sonar-project.properties
          echo "sonar.sources=." >> sonar-project.properties  
          echo "sonar.php.coverage.reportPaths=coverage.xml" >> sonar-project.properties  
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}     
 
