name: NODE CI
on: [push]
jobs:
  test-build:
    name: Test & build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add Grafana annotation
        id: grafana
        uses: hexionas/grafana-annotation-action@v0
        with:
          grafanaHost: "http://34.228.197.176:3000"
          grafanaToken: glsa_NDE8hzapE5O9tRnsAEcvXsW9HpHk9vDH_58060308
          grafanaText: |
            This is an example of the text that
            will be present on the annotation
          grafanaTags: |
            type:performance
            service:sre-smart-scaling-api
      - uses: actions/setup-node@v1
        with:
          node-version: 15
      - run: sudo apt install python2-minimal  -y   
      - name: Add Grafana annotation
        # You may pin to the exact commit or the version.
        # uses: frankie567/grafana-annotation-action@2060c74ecf2b711a6ed8b13f380e579b2ecbcebd
        uses: frankie567/grafana-annotation-action@v1.0.2
        with:
          # Grafana API host
          apiHost: http://34.228.197.176:3000
          # Grafana API token
          apiToken: glsa_NDE8hzapE5O9tRnsAEcvXsW9HpHk9vDH_58060308
          # Text of the annotation
          text: demogithub
          # Id. of the dashboard to add the annotation on. If not provided, will be global to all dashboards.
          #dashboardId: # optional
          # Id. of the panel to add the annotation on. If not provided, will be global to all panels.
          #panelId: # optional
          # Comma-separated list of tags assigned to the annotation.
          #tags: # optional
          
      - run: yarn
      # Build modules
      - run: yarn build
      # Build sonar reports
      - run: yarn test-coverage
      - name: Create file ${{ inputs.tag }}
        run: |
          ls
          echo "sonar.branch.name=master" >> sonar-project.properties
          echo "sonar.organization=cabunga-github" >> sonar-project.properties
          echo "sonar.projectKey=cabunga-github_node" >> sonar-project.properties
          echo "sonar.sources=." >> sonar-project.properties  
          echo "sonar.javascript.lcov.reportPaths=./coverage/lcov.info" >> sonar-project.properties  
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}     
 
